apiVersion: apps/v1
kind: Deployment
metadata:
 name: myapp
spec:
 replicas: 2
 selector:
  matchLabels:
   app: argo-web
 template:
  metadata:
    labels:
     app: argo-web
  spec:Â 
   containers:
   - name: c1
     image: kvsmanian/testfb:v27
     imagePullPolicy: Always
     stdin: true
     tty: true